apiVersion: aws.platform.upbound.io/v1alpha1
kind: Karpenter
metadata:
  name: configuration-aws-eks-karpenter
  namespace: default
spec:
  parameters:
    clusterNameSelector:
      matchLabels:
        crossplane.io/composite: configuration-aws-eks-karpenter
    id: configuration-aws-eks-karpenter
    region: us-west-2
